//! In-memory + on-disk message store.
//!
//! Every message has a `source` so the UI can render them differently:
//!   - `human`   : inbound from a contact (received)
//!   - `manual`  : outbound, typed by the operator in this app
//!   - `ai`      : outbound, generated by the AI bridge
//!   - `system`  : status/log lines
//!
//! Persisted as line-delimited JSON to ~/.local/share/signal-whatsapp-hub/messages.jsonl
//! so history survives restarts.

use chrono::Utc;
use serde::{Deserialize, Serialize};
use std::fs::{create_dir_all, OpenOptions};
use std::io::{BufRead, BufReader, Write};
use std::path::PathBuf;
use std::sync::Mutex;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    pub id: String,
    /// "signal" | "whatsapp"
    pub platform: String,
    /// "in" | "out"
    pub direction: String,
    /// "human" | "manual" | "ai" | "system"
    pub source: String,
    /// contact phone/jid or name (the other party)
    pub peer: String,
    pub peer_name: String,
    pub text: String,
    /// unix seconds
    pub ts: f64,
}

impl Message {
    pub fn new(
        platform: &str,
        direction: &str,
        source: &str,
        peer: &str,
        peer_name: &str,
        text: &str,
    ) -> Self {
        let ts = Utc::now().timestamp_millis() as f64 / 1000.0;
        Message {
            id: format!("{}-{}", (ts * 1000.0) as u64, rand_suffix()),
            platform: platform.to_string(),
            direction: direction.to_string(),
            source: source.to_string(),
            peer: peer.to_string(),
            peer_name: peer_name.to_string(),
            text: text.to_string(),
            ts,
        }
    }
}

fn rand_suffix() -> String {
    // cheap unique-ish suffix without pulling in rand crate
    use std::time::{SystemTime, UNIX_EPOCH};
    let n = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.subsec_nanos())
        .unwrap_or(0);
    format!("{:06x}", n & 0xffffff)
}

fn store_path() -> PathBuf {
    let dir = dirs::data_dir()
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join("signal-whatsapp-hub");
    let _ = create_dir_all(&dir);
    dir.join("messages.jsonl")
}

pub struct Store {
    msgs: Mutex<Vec<Message>>,
}

impl Store {
    pub fn new() -> Self {
        let msgs = load_from_disk();
        Store {
            msgs: Mutex::new(msgs),
        }
    }

    /// Add a message, persist it, and return a clone.
    pub fn add(&self, m: Message) -> Message {
        append_to_disk(&m);
        let mut guard = self.msgs.lock().unwrap();
        guard.push(m.clone());
        // keep memory bounded
        let len = guard.len();
        if len > 5000 {
            guard.drain(0..(len - 5000));
        }
        m
    }

    /// One-time import of an existing CSV so prior chat history shows up
    /// immediately (set the `HUB_IMPORT_CSV` env var to enable). Idempotent: a
    /// marker file prevents re-importing on every launch. Returns the number of
    /// messages imported.
    ///
    /// Expected columns (header row skipped):
    ///   `timestamp_iso, direction(in|out), platform(signal|whatsapp), phone,
    ///    sender_name, <ignored>, text`
    pub fn import_legacy_csv(&self, csv_path: &std::path::Path) -> usize {
        let marker = store_path().with_file_name("legacy_imported.marker");
        if marker.exists() || !csv_path.exists() {
            return 0;
        }
        let content = match std::fs::read_to_string(csv_path) {
            Ok(c) => c,
            Err(_) => return 0,
        };
        let mut imported = Vec::new();
        for (i, line) in content.lines().enumerate() {
            if i == 0 {
                continue; // header
            }
            if let Some(m) = parse_legacy_row(line) {
                imported.push(m);
            }
        }
        let n = imported.len();
        if n > 0 {
            let mut guard = self.msgs.lock().unwrap();
            for m in &imported {
                append_to_disk(m);
            }
            // prepend legacy history before any live messages, then sort by ts
            let mut all: Vec<Message> = imported;
            all.append(&mut guard);
            all.sort_by(|a, b| a.ts.partial_cmp(&b.ts).unwrap_or(std::cmp::Ordering::Equal));
            *guard = all;
        }
        let _ = std::fs::write(&marker, "imported");
        n
    }

    /// All messages for a platform, optionally filtered to a peer.
    pub fn list(&self, platform: &str, peer: Option<&str>, limit: usize) -> Vec<Message> {
        let guard = self.msgs.lock().unwrap();
        let mut v: Vec<Message> = guard
            .iter()
            .filter(|m| m.platform == platform)
            .filter(|m| match peer {
                Some(p) => m.peer == p,
                None => true,
            })
            .cloned()
            .collect();
        if v.len() > limit {
            v = v.split_off(v.len() - limit);
        }
        v
    }

    /// Distinct peers for a platform, most-recent first, with last message.
    pub fn conversations(&self, platform: &str) -> Vec<Conversation> {
        let guard = self.msgs.lock().unwrap();
        let mut map: std::collections::HashMap<String, Conversation> =
            std::collections::HashMap::new();
        for m in guard.iter().filter(|m| m.platform == platform) {
            let entry = map.entry(m.peer.clone()).or_insert_with(|| Conversation {
                peer: m.peer.clone(),
                peer_name: m.peer_name.clone(),
                last_text: String::new(),
                last_ts: 0.0,
                unread: 0,
            });
            if !m.peer_name.is_empty() {
                entry.peer_name = m.peer_name.clone();
            }
            if m.ts >= entry.last_ts {
                entry.last_ts = m.ts;
                entry.last_text = m.text.clone();
            }
        }
        let mut v: Vec<Conversation> = map.into_values().collect();
        v.sort_by(|a, b| b.last_ts.partial_cmp(&a.last_ts).unwrap());
        v
    }

    /// Aggregate stats for a platform, for the empty-state dashboard.
    pub fn stats(&self, platform: &str) -> PlatformStats {
        let guard = self.msgs.lock().unwrap();
        let mut s = PlatformStats::default();
        let mut peers = std::collections::HashSet::new();
        for m in guard.iter().filter(|m| m.platform == platform) {
            s.total += 1;
            peers.insert(m.peer.clone());
            match m.direction.as_str() {
                "in" => s.received += 1,
                "out" => {
                    s.sent += 1;
                    if m.source == "ai" {
                        s.ai_sent += 1;
                    } else {
                        s.manual_sent += 1;
                    }
                }
                _ => {}
            }
            if m.ts > s.last_activity_ts {
                s.last_activity_ts = m.ts;
            }
        }
        s.conversations = peers.len() as u64;
        s
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct PlatformStats {
    pub total: u64,
    pub received: u64,
    pub sent: u64,
    pub ai_sent: u64,
    pub manual_sent: u64,
    pub conversations: u64,
    pub last_activity_ts: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Conversation {
    pub peer: String,
    pub peer_name: String,
    pub last_text: String,
    pub last_ts: f64,
    pub unread: u32,
}

fn load_from_disk() -> Vec<Message> {
    let path = store_path();
    let file = match std::fs::File::open(&path) {
        Ok(f) => f,
        Err(_) => return Vec::new(),
    };
    let reader = BufReader::new(file);
    let mut out = Vec::new();
    for line in reader.lines().map_while(Result::ok) {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if let Ok(m) = serde_json::from_str::<Message>(line) {
            out.push(m);
        }
    }
    // keep only the last 5000 on load
    let len = out.len();
    if len > 5000 {
        out.split_off(len - 5000)
    } else {
        out
    }
}

fn append_to_disk(m: &Message) {
    let path = store_path();
    if let Ok(mut f) = OpenOptions::new().create(true).append(true).open(path) {
        if let Ok(line) = serde_json::to_string(m) {
            let _ = writeln!(f, "{}", line);
        }
    }
}

/// Split a CSV line into fields, honouring double-quoted fields that may
/// contain commas (the old bridge quotes the `content` column).
fn split_csv(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut cur = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' => {
                if in_quotes && chars.peek() == Some(&'"') {
                    cur.push('"'); // escaped quote
                    chars.next();
                } else {
                    in_quotes = !in_quotes;
                }
            }
            ',' if !in_quotes => {
                fields.push(std::mem::take(&mut cur));
            }
            _ => cur.push(c),
        }
    }
    fields.push(cur);
    fields
}

/// Parse one row of the legacy messages.csv:
/// timestamp,direction,platform,phone,sender_name,user_code,content
fn parse_legacy_row(line: &str) -> Option<Message> {
    let f = split_csv(line);
    if f.len() < 7 {
        return None;
    }
    let ts_raw = f[0].trim();
    let direction = f[1].trim().to_lowercase();
    let platform = f[2].trim().to_lowercase();
    let phone = f[3].trim();
    let sender_name = f[4].trim();
    let content = f[6].trim();
    if content.is_empty() || (platform != "signal" && platform != "whatsapp") {
        return None;
    }
    let ts = parse_iso_ts(ts_raw);
    // legacy "out" = sent by the AI bridge; "in" = received human message
    let source = if direction == "out" { "ai" } else { "human" };
    Some(Message {
        id: format!("legacy-{}", (ts * 1000.0) as u64),
        platform,
        direction: if direction == "out" { "out".into() } else { "in".into() },
        source: source.into(),
        peer: phone.to_string(),
        peer_name: sender_name.to_string(),
        text: content.to_string(),
        ts,
    })
}

/// Parse an ISO-8601 timestamp (with optional microseconds, optional Z) to
/// unix seconds. Best-effort; returns 0.0 on failure.
fn parse_iso_ts(s: &str) -> f64 {
    let s = s.trim();
    if s.is_empty() {
        return 0.0;
    }
    let cleaned = s.replace('Z', "+00:00");
    // try full RFC3339 first
    if let Ok(dt) = chrono::DateTime::parse_from_rfc3339(&cleaned) {
        return dt.timestamp() as f64 + (dt.timestamp_subsec_millis() as f64 / 1000.0);
    }
    // try naive (no tz) with fractional seconds, assume UTC
    let naive_str = cleaned.split('+').next().unwrap_or(&cleaned);
    for fmt in ["%Y-%m-%dT%H:%M:%S%.f", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S%.f"] {
        if let Ok(ndt) = chrono::NaiveDateTime::parse_from_str(naive_str, fmt) {
            return ndt.and_utc().timestamp() as f64;
        }
    }
    0.0
}
